token:
  expiration_time: 864000000
  secure: '{cipher}AYAcqbITaZbWBmEp+HA7k3v36u4z+0jTRXOZBgPItO0tzPPooB4QQk6EIuaAUFF0rMcCSqyiMLZVunMkDM9XMsYtod8E3Z95Bh6N5VkLPekW04Jblc4YqOT7c+P6YKDG8S+3yqvjKdUs3ktwosjhDj5XZvxd5gnwJ6WCuFAGLy4wzi3xx/jMkgxcUq8sgZacguPgZ6jtjSTAZR9AIvB03QZMEc//2YJJkU80n4Md0d54aTWeQp+2br9mBylHy7GtIs+5mV2RfO5pZeZS7kN18efvze4xKSZA4QB+qe1hJLaODK0KmxhmpzW8rjrIf9f3SC7+OxsMJTYi7WA2jHHNF8le1rzqO2rdT7x/ahQdrLS4mlM85hCiv1zhB5CoRpf8vheCsYhU9Xhw4Rzjx3zNmUV7DISF3pH87krMqPUl936hl9e4mf4yi/k5QXbz0q8uc308iCkjg6UxDJYvHadrRwwebh98tg2p29u0FTg6mH9Ja2+EePXEAEdJZkagRSomLOEPWbr26HfGhkj/00IYSW1aveJFcmxEaBwT0gaTOYaeg2m82cKJilq+JfIvvRclKwESksTyiZloo1A/T+1UXbWxP2qRal0m9vGIb90pYi1/9uN2mAkpxp2jPSGac3Xoh0o='
#  secret: user_token_git_very-long-and-secure-hmac-secret-key-1234567890123456

gateway:
  ip: localhost